services:
  mail:
    image: mailhog/mailhog
    ports:
        - 8025:8025
        - 1025:1025

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_DB: bd-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: bd-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      DATABASE_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
    db-data:
