version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=bd-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5433/bd-dev
      - DJANGO_SETTINGS_MODULE=config.settings.test
    depends_on:
      db:
        condition: service_healthy
