
services:
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

  db:
    image: postgres:15
    command: -p 5433
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=bd-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py loaddata admin_interface_theme_foundation.json &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
