image: python:3.11-slim

stages:
  - test

test_job:
  stage: test
  tags:
    - python
    - django
    - production
  script:
    - echo "Pipeline triggered by change"
    - python --version
    - echo "Current branch: $CI_COMMIT_BRANCH"
    - echo "Commit message: $CI_COMMIT_MESSAGE"
