image: python:3.11-slim

stages:
  - test

test_job:
  stage: test
  tags:  # Suas tags configuradas
    - python
    - django
    - production
  script:
    - echo "Testing pipeline execution"
    - python --version
    - pwd
    - ls -la
    - echo "CI_PROJECT_DIR: $CI_PROJECT_DIR"
    - echo "Pipeline test completed successfully!"
