# Generated by Django 5.1.2 on 2024-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativacaoconta',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Ativação de Conta', 'verbose_name_plural': 'Ativações de Contas'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil'),
        ),
    ]
