# Generated by Django 5.1.2 on 2024-10-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_ativacaoconta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de Perfil'),
        ),
    ]
