# Generated by Django 5.1.2 on 2024-10-19 22:03

import contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_perfilusuario_avatar_url_alter_perfilusuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=contas.models.upload_to, verbose_name='Foto de Perfil'),
        ),
    ]
