# Generated by Django 4.2.16 on 2024-11-09 16:08

import apps.contas.models.perfil_usuario
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "username",
                    models.CharField(max_length=255, verbose_name="Nome de Usuário"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.contas.models.perfil_usuario.upload_to,
                        verbose_name="Foto de Perfil",
                    ),
                ),
                ("nome", models.CharField(max_length=60, verbose_name="Nome Completo")),
                (
                    "cpf",
                    models.CharField(
                        help_text="Digite apenas os números do CPF, sem pontos ou traços",
                        max_length=11,
                        unique=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_cadastro",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "email_confirmado",
                    models.BooleanField(default=False, verbose_name="Email Confirmado"),
                ),
                (
                    "codigo_verificacao_email",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Código de Verificação",
                    ),
                ),
                (
                    "celular",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="Digite o número no formato: DDD9XXXX-XXXX",
                        max_length=128,
                        region=None,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "ordering": ["-data_cadastro"],
            },
        ),
        migrations.CreateModel(
            name="AtivacaoConta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_ativacao",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        verbose_name="Código de Ativação",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "tentativas",
                    models.IntegerField(
                        default=0, verbose_name="Tentativas de Ativação"
                    ),
                ),
                (
                    "expira_em",
                    models.DateTimeField(null=True, verbose_name="Data de Expiração"),
                ),
                (
                    "email_enviado",
                    models.TextField(
                        blank=True, null=True, verbose_name="Email Enviado"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacao_email",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ativação de Conta",
                "verbose_name_plural": "Ativações de Contas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
