# Generated by Django 4.2.16 on 2024-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario",
                    models.EmailField(max_length=254, verbose_name="Destinatário"),
                ),
                ("assunto", models.CharField(max_length=255, verbose_name="Assunto")),
                ("conteudo", models.TextField(verbose_name="Conteúdo")),
                ("codigo", models.CharField(max_length=10, verbose_name="Código")),
                (
                    "data_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ativacao", "Ativação de Conta"),
                            ("novo_codigo", "Novo Código"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sucesso", "Sucesso"), ("erro", "Erro")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Email",
                "verbose_name_plural": "Logs de Email",
                "ordering": ["-data_envio"],
            },
        ),
    ]
